language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
  - phpenv rehash

script:
  - phpunit
  - output=$(php php-cs-fixer.phar fix -v --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;